### ISSUE TITLE
crd-model-gen should enforce that enums are UPPERCASE and don't contain special characters

### ISSUE THREAD

**Issue by ksumit** [kubernetes-client/gen#196]
While working on a CRD, i had two enum patterns that didn't work out:
1. Enums with lowercase or mixed case names
2. Enums with special characters in the names

Example:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
...
spec:
...
  versions:
    - name: v1alpha1
...
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
...
                type:
                  type: string
                  # First pattern with lowercase or mixed case names
                  enum:
                    - apple
                    - banana
                    - WaterMelon
                  default: apple
                  description: "Type of fruit"
...
...
                fileName:
                  type: string
                  # Second pattern with names containing special characters
                  enum:
                    - log4j.properties
                    - web.xml
                    - server.xml
...
```

Technically these are not valid patterns for enum names in Java (atleast the second pattern wouldn't even compile) and crd-model-gen happily does the right thing by transforming these names to UPPERCASE and replacing special characters with "_" putting the values in the enum like below:
```
// for the first pattern
  public static enum TypeEnum {
    APPLE("apple"),
    BANANA("banana"),
    WATERMELON("WaterMelon");

// for the second pattern
  public static enum FileNameEnum {
    LOG4J_PROPERTIES("log4j.properties"),
    WEB_XML("web.xml"),
    SERVER_XML("server.xml");
```

The problem however happens when loading a CR with such enum values using Yaml class that is provided with java implementation of kubernetes-client.

SnakeYaml [started supporting a loader option to ignore case while loading enums starting version 1.28](https://github.com/asomov/snakeyaml/pull/14/files) and I have a corresponding change [here](https://github.com/ksumit/kubernetes-client-java/commit/aac5e5192dd54a5f54856d757ffb4d2083f7addc) to consume the same. However i am not able to justify that the second pattern should even be supported. And that brings to me to the thought, should crd-model-gen enforce that enum names are always UPPERCASE and don't container special characters other than "_". 

Thoughts?
